export { NotFoundPage } from "./NotFoundPage/NotFoundPage";
export { MainPage } from "./MainPage";
export { LoginPage } from "./LoginPage";
export { RegistrationPage } from "./RegistrationPage";
export { PostsPage } from "./PostsPage";
export { PostPage } from "./PostPage";
export { CreatePostPage } from "./CreatePostPage";
export { ProfilePage } from "./ProfilePage";
export { ContactsPage } from "./ContactsPage";
